# SITE CONFIGURATION
title: Coded Chai # your site title
author: Connor Hasting # You
description: > # Meta description of Homepage
  Connor Hasting's Personal Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://codedchai.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Connor Hasting
  links:
    - https://github.com/codedchai

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}

tagline: >
  Connor Hasting's Personal Website

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: connorhhasting@gmai # email for form submission

github_username:  codedchai # replace with your_github_username or comment to remove link from footer
instagram_username: codedchai # replace with your_instagram_username or comment to remove link from footer

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
